services:
 rabbitmq:
  build: .
  container_name: rabbitmq
  hostname: rabbitmq
  restart: always
  environment:
    - RABBITMQ_DEFAULT_USER=root
    - RABBITMQ_DEFAULT_PASS=root
  ports:
    - "15672:15672"
    - "5672:5672"
  networks:
    - mq
  volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    - mq-plugins:/plugins

volumes:
  mq-plugins:
    driver: local
  rabbitmq-data:
    driver: local

networks:
  mq:
    driver: bridge
